=== Paidpar345/PPC_PRAC2/PPC_Practica2/target/classes/distribucion.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="VariableType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="unidad" type="xs:string"/>
            <xs:element name="valor" type="xs:double"/> 
        </xs:sequence>
    </xs:complexType>

    <xs:element name="MensajeDistribucion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Variable" type="VariableType" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="idServidor" type="xs:string" use="required"/>
            <xs:attribute name="codificacion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="XML"/>
                        <xs:enumeration value="JSON"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Paidpar345/PPC_PRAC2/PPC_Practica2/rx/SERV-1_XML_1764156297219.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<MensajeDistribucion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" codificacion="XML" idServidor="SERV-1" xsi:noNamespaceSchemaLocation="recursos/distribucion.xsd">
    <Variable>
        <nombre>temperatura</nombre>
        <unidad>°C</unidad>
        <valor>24.62</valor>
    </Variable>
    <Variable>
        <nombre>dióxido de azufre (SO2)</nombre>
        <unidad>µg/m³</unidad>
        <valor>27.93</valor>
    </Variable>
    <Variable>
        <nombre>ozono (O3)</nombre>
        <unidad>µg/m³</unidad>
        <valor>32.57</valor>
    </Variable>
</MensajeDistribucion>

=== Paidpar345/PPC_PRAC2/PPC_Practica2/rx/SERV-2_XML_1764154423606.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<MensajeDistribucion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" codificacion="XML" idServidor="SERV-2" xsi:noNamespaceSchemaLocation="recursos/distribucion.xsd">
    <Variable>
        <nombre>humedad relativa</nombre>
        <unidad>%</unidad>
        <valor>68.7</valor>
    </Variable>
    <Variable>
        <nombre>dióxido de nitrógeno (NO2)</nombre>
        <unidad>µg/m³</unidad>
        <valor>43.01</valor>
    </Variable>
    <Variable>
        <nombre>partículas en suspensión (PM10)</nombre>
        <unidad>µg/m³</unidad>
        <valor>38.42</valor>
    </Variable>
    <Variable>
        <nombre>ozono (O3)</nombre>
        <unidad>µg/m³</unidad>
        <valor>26.83</valor>
    </Variable>
</MensajeDistribucion>

=== Paidpar345/PPC_PRAC2/PPC_Practica2/rx/SERV-3_XML_1764156303292.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<MensajeDistribucion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" codificacion="XML" idServidor="SERV-3" xsi:noNamespaceSchemaLocation="recursos/distribucion.xsd">
    <Variable>
        <nombre>temperatura</nombre>
        <unidad>°C</unidad>
        <valor>20.12</valor>
    </Variable>
    <Variable>
        <nombre>humedad relativa</nombre>
        <unidad>%</unidad>
        <valor>57.77</valor>
    </Variable>
    <Variable>
        <nombre>partículas en suspensión (PM10)</nombre>
        <unidad>µg/m³</unidad>
        <valor>25.59</valor>
    </Variable>
</MensajeDistribucion>
